name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies and build
        working-directory: frontend
        run: |
          npm ci
          npm run build
        env:
          CI: false

      - name: Deploy to Firebase Hosting
        working-directory: frontend
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_EPL_RESOURCE }}
          channelId: live
          projectId: epl-resource
