name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies and build
        working-directory: frontend  # Set the working directory to /frontend
        run: |
          npm ci
          npm run build

      - name: Run ESLint (ignore warnings)
        working-directory: frontend  # Set the working directory to /frontend
        run: |
          npm run lint -- --max-warnings=0
          # This ensures ESLint exits with a success status even if there are warnings

      - name: Deploy to Firebase Hosting
        run: |
          npm run build  # Run the build again if needed
          firebase deploy --only hosting
        env:
          CI: true  # Ensure CI is recognized as true
