name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies and build
        working-directory: frontend  # Set the working directory to /frontend
        env:
          CI: false
        run: |
          npm ci
          npm run build
      - name: Deploy to Firebase Hosting
        run: |
          firebase deploy --only hosting
